#ifndef SHAREDHANDLERS_GLOBAL_H
#define SHAREDHANDLERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAREDHANDLERS_LIBRARY)
#  define SHAREDHANDLERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAREDHANDLERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAREDHANDLERS_GLOBAL_H
